### ISSUE TITLE
createLineItems error

### ISSUE THREAD

**Issue by tacshooter** [spanishdict/example-dfp-line-item-generator#18]
When I call createLineItems with the object below, I get a soap error. I tried using the code directly from the createCampaign example, but ran into errors straight away with attributes of LineItem that don't exist. I went through the wsdl docs and changed up the LineItem, but still... Any help you could give sure would be appreciated... 

```
[
  {
      "orderId": 428533037,
      "name": "Tester",
      "externalId": 55,
      "startDateTime": {
        "date": {
          "year": 2016,
          "month": 3,
          "day": 16
        },
        "hour": 19,
        "minute": 0,
        "second": 0,
        "timeZoneID": "America/Chicago"
      },
      "endDateTime": {
        "date": {
          "year": 2016,
          "month": 3,
          "day": 30
        },
        "hour": 19,
        "minute": 0,
        "second": 0,
        "timeZoneID": "America/Chicago"
      },
      "creativeRotationType": "WEIGHT",
      "lineItemType": "STANDARD",
      "allowOverbook": true,
      "skipInventoryCheck": true,
      "primaryGoal": {
        "goalType": "LIFETIME",
        "unitType": "IMPRESSIONS",
        "units": 122
      },
      "targeting": {
        "inventoryTargeting": {
          "targetedPlacementIds": 3441557
        }
      },
      "costType": "CPM",
      "creativePlaceholders": [
        {
          "size": {
            "width": 728,
            "height": 90,
            "isAspectRatio": false
          }
        }
      ],
      "costPerUnit": {
        "currencyCode": "USD",
        "microAmount": 2000000
      }
    }
]
```

ERROR:

```
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Body>
    <soap:Fault>
      <faultcode>soap:Client</faultcode>
      <faultstring>Unmarshalling Error: cvc-complex-type.2.4.a: Invalid content was found starting with element 'costType'. One of '{"https://www.google.com/apis/ads/publisher/v201602":creativeTargetings}' is expected. </faultstring>
    </soap:Fault>
  </soap:Body>
</soap:Envelope>
```

**Comment by JuanCaicedo** [comment]
What's the createCampaign example?

Yes, I've seen this error before and it's incredibly frustrating! It has to do with properties in the JSON not being in the correct order. If you're able to change the JSON definition, I would order it following [this example](https://github.com/spanishdict/node-google-dfp-wrapper/blob/master/fixtures/input/line-item.json). If you need to dynamically add properties, let me know and I can recommend another approach.

**Comment by tacshooter** [comment]
Wow, that was dumb. I had several GitHub tabs opened and I opened the issue on the wrong one!!! What's even better about that is that someone was still able to offer advice! I'm off to try your advice now... Sorry for the confusion and thanks!

**Comment by JuanCaicedo** [comment]
Good luck! Please close the issue if that works :smiley:

**Comment by tacshooter** [comment]
That did work, even though I posted it in the wrong project entirely. Much appreciated Juan!

**Comment by fleeco** [comment]
@JuanCaicedo I just wanted to say that I spent about 3 hours debugging this, and your answer solved my problem.  I can't believe the order of the JSON properties mattered - I was about to lose my damn mind.  Thanks again!

**Comment by JuanCaicedo** [comment]
@fleeco, I know that's crazy!
