### ISSUE TITLE
generate-refresh-token.js requires lib/creative, but it's not clear what that is.

### ISSUE THREAD

**Issue by kitwestneat** [spanishdict/example-dfp-line-item-generator#6]
I got around it by commenting out the require statement, and it worked fine.

**Comment by JuanCaicedo** [comment]
@kitwestneat sorry for the slow response. I copied over an old project to get this one started, and a lot of the code in generate-refresh-token.js is left over from then and unused. I'll be fixing this in an update I'll be pushing in the next couple weeks!

**Comment by JuanCaicedo** [comment]
I've cleaned up the getting started procedure and have moved it over to https://github.com/spanishdict/node-google-dfp-wrapper. Hopefully this helps!
