### ISSUE TITLE
Got error when run npm install 

### ISSUE THREAD

**Issue by hileon** [spanishdict/example-dfp-line-item-generator#7]
When I try to use this code, use `npm install` to install dependency npm package, it always report this error.
Can you help to point out where I am wrong?

Tested under NodeJS 4.2.4

![lz 2016-01-04 at 5 20 54 pm](https://cloud.githubusercontent.com/assets/109745/12086743/e77831c2-b307-11e5-8031-286673f54a8b.png)

**Comment by JuanCaicedo** [comment]
Hmm, that's really weird, but I've only ever tried this with v0.10.36. I can try this out next week and report what I find.

**Comment by JuanCaicedo** [comment]
I think this error comes from the fact that the version of level that we're using isn't compatible with node v4+. From what I can tell, it's possible to update to v1.4.0 without any problems, but I'm going to do some more testing and then submit a PR.

**Comment by JuanCaicedo** [comment]
@hileon if you want, you can go ahead and try that as well. Let me know if you have any problems

**Comment by JuanCaicedo** [comment]
According to https://github.com/Level/levelup/issues/378, they follow semver, so there should be no breaking changes by updating to 1.4.0

**Comment by StaymanHou** [comment]
I ran into a similar problem. Updating `level` to 1.4.0 fixed it.

**Comment by JuanCaicedo** [comment]
Awesome, glad to know that fixed it! I'll follow up with a PR updating that

**Comment by JuanCaicedo** [comment]
Addressed by #34
